name : call test worlkflow

on:
 push: 
  branches: main
  
  
jobs:
  
  callTestWorkflow:
   uses: Dilipkumar1127/test-workflows/.github/workflows/test.yml@main
   with:
     workingDirectory: "./"
     inputDownloadname: inputArtifact
     inputArtifactPath: inputArtifactPath
     inputCompression: inputCompress
     outputDownloadname: outputArtifact
     outputArtifactPath: outputArtifactPath
     outputCompression: outputCompress
     CompressArtifacts: true
